version: '3'
services:
  microcontroller_proxy:
    container_name: microcontroller_proxy
    build: .
    image: techthetime-highlevel
    command: bash -c "cd /hl/ros_workspace/src/microcontroller_proxy/lib && git submodule init && git submodule update --remote && \
      cd /hl/ros_workspace/src/microcontroller_proxy/src && git submodule init && git submodule update --remote && \ 
      cd /hl/build_tool && ./build-hl.sh -v -p microcontroller_proxy && \
      cd /hl/ros_workspace && . install/setup.bash && \
      ros2 run microcontroller_proxy microcontroller_proxy"
  manager:
    container_name: manager
    image: techthetime-highlevel
    # command: bash -c "export TERM=vt100 && cd build_tool && ./build-hl.sh -v -p manager && cd ../ros_workspace && . install/setup.bash && \
    #          compgen -c | grep ros && ros2 run manager manager"
    command: bash -c "compgen -c | grep ros"
    depends_on:
      - microcontroller_proxy
    links:
      - microcontroller_proxy
