version: '3'
services:
  microcontroller_proxy:
    container_name: microcontroller_proxy
    build: .
    image: techthetime-highlevel
    command: bash -c "export TERM=vt100 && cd /hl/build_tool && ./build-hl.sh -v -p microcontroller_proxy && cd /hl/ros_workspace && source install/setup.bash && ros2 run microcontroller_proxy microcontroller_proxy"
  manager:
    container_name: manager
    image: techthetime-highlevel
    command: bash -c "export TERM=vt100 && cd /hl/build_tool && ./build-hl.sh -v -p manager && cd /hl/ros_workspace && source install/setup.bash && sleep 20 && ros2 run manager manager"
    depends_on:
      - microcontroller_proxy
    links:
      - microcontroller_proxy
