name: Doxygen Documentation Deploy

on:
        push:
                branches: [ main ]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v2
                        submodules: true
                - name: Checkout Awesome CSS
                run: |
                git submodule set-branch --branch v2.0.2 doxygen-awesome-css

                - name: Doxygen Documentation Deploy
                  uses: mattnotmitt/doxygen-action@v1.1.0
                  with:
                          doxyfile-path: "./Doxyfile"
                          working-directory: "."
                - name: Deploy
                  uses: peaceiris/actions-gh-pages@v3
                  with:
                          github_token: ${{ secrets.GITHUB_TOKEN }}
                          publish_dir: ./html

