name: Doxygen Documentation Deploy

on:
        push:
                branches: [ main ]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                - uses: actions/checkout@v2
                - name: Doxygen Documentation Deploy
                  uses: mattnotmitt/doxygen-action@v1.1.0
                  with:
                          doxyfile-path: "./ros_workspace/Doxyfile"
                          working-directory: "."
                - name: Deploy
                  uses: peaceiris/actions-gh-pages@v3
                  with:
                          github_token: ${{ secrets.GITHUB_TOKEN }}
                          publish_dir: ./ros_workspace/doc/html

